[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

rpc_endpoints = { arbitrum = "${RPC_ARBITRUM}" }
fs_permissions = [{ access = "read-write", path = "./"}]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config